github.com:
    git_protocol: ssh
    users:
        jtjlehi:
            oauth_token: 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
    user: jtjlehi
    oauth_token: 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
